# -*- coding: utf-8 -*-
"""
Bulk restauration des accents francais dans les writers FinSight IA.

Strategie :
- Pour chaque fichier cible, on parcourt et on applique un dict de remplacements
  mot par mot. On ne touche QUE le contenu des strings (pas les commentaires
  Python ni les noms de variables).
- Niveau (b) : accents complets, apostrophes droites ', guillemets francais << >>.
- Apres execution, verification syntaxique avec py_compile.

Usage : python tools/restore_accents.py
"""
from __future__ import annotations

import re
import sys
import py_compile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ============================================================================
# DICTIONNAIRE DE REMPLACEMENT — mot a mot, accents restaures
# ============================================================================
# IMPORTANT : ordonner du plus long au plus court pour eviter les sous-chaines
#  ex : "presente" doit etre traite avant "ente"
# Regle : seules les formes sans accent sont restaurees ; formes deja accentuees
#  ne sont pas dans le dict (donc inchangees).
# ============================================================================

REPLACEMENTS = {
    # === Verbes / formes verbales tres frequentes ===
    "genere":          "génère",
    "generee":         "générée",
    "generees":        "générées",
    "genees":          "génées",
    "genere par":      "généré par",
    "generes":         "générés",
    "generation":      "génération",
    "generations":     "générations",
    "presente":        "présente",
    "presentee":       "présentée",
    "presentees":      "présentées",
    "presentes":       "présentés",
    "presentent":      "présentent",
    "represente":      "représente",
    "representee":     "représentée",
    "representees":    "représentées",
    "represente par":  "représenté par",
    "represente une":  "représente une",
    "reflete":         "reflète",
    "refletant":       "reflétant",
    "reflete une":     "reflète une",
    "reflete un":      "reflète un",
    "considere":       "considère",
    "considerees":     "considérées",
    "considere comme": "considéré comme",
    "integre":         "intègre",
    "integree":        "intégrée",
    "integrees":       "intégrées",
    "integres":        "intégrés",
    "integration":     "intégration",
    "espere":          "espère",
    "delivre":         "délivre",
    "delivrer":        "délivrer",
    "delivres":        "délivrés",
    "verifier":        "vérifier",
    "verifie":         "vérifie",
    "verifiee":        "vérifiée",
    "verifies":        "vérifiés",
    "verification":    "vérification",
    "deteriore":       "détériore",
    "deterioree":      "détériorée",
    "deterioration":   "détérioration",
    "ameliore":        "améliore",
    "amelioree":       "améliorée",
    "amelioration":    "amélioration",
    "ameliorations":   "améliorations",
    "elabore":         "élabore",
    "elaboree":        "élaborée",
    "elabores":        "élaborés",
    "compresse":       "compresse",
    "ralentit":        "ralentit",
    "ralentissement":  "ralentissement",
    "souligne":        "souligne",
    "souligne une":    "souligne une",
    "calibre":         "calibré",
    "calibree":        "calibrée",
    "calibrer":        "calibrer",
    "calibration":     "calibration",
    "agree":           "agréé",
    "agreement":       "agreement",
    "agreee":          "agréée",
    "agrees":          "agréés",
    "couvre":          "couvre",
    "operer":          "opérer",
    "opere":           "opère",
    "operee":          "opérée",
    "exprime":         "exprime",
    "estime":          "estime",
    "estimee":         "estimée",
    "estimes":         "estimés",
    "estimer":         "estimer",
    "estimation":      "estimation",
    "deduit":          "déduit",
    "decompose":       "décompose",
    "decoule":         "découle",
    "decoulant":       "découlant",
    "ecoute":          "écoute",
    "deroule":         "déroule",
    "deroule sur":     "déroule sur",
    "interprete":      "interprète",
    "interpretation":  "interprétation",
    "interpretee":     "interprétée",
    "deceler":         "déceler",
    "decele":          "décèle",
    "evaluer":         "évaluer",
    "evalue":          "évalue",
    "evaluation":      "évaluation",
    "reevaluer":       "réévaluer",
    "reevaluation":    "réévaluation",
    "evolue":          "évolue",
    "evolution":       "évolution",
    "evolutions":      "évolutions",
    "envisage":        "envisage",
    "anticipe":        "anticipe",
    "anticipation":    "anticipation",
    "anticipations":   "anticipations",
    "amplifie":        "amplifie",
    "amplifiee":       "amplifiée",
    "etabli":          "établi",
    "etablie":         "établie",
    "etablies":        "établies",
    "etablit":         "établit",
    "valide":          "valide",
    "validation":      "validation",
    "ferme":           "ferme",
    "fermee":          "fermée",
    "ouvre":           "ouvre",
    "ouverte":         "ouverte",

    # === Noms communs (frequence elevee) ===
    "donnee":          "donnée",
    "donnees":         "données",
    "qualite":         "qualité",
    "qualites":        "qualités",
    "valorisation":    "valorisation",
    "valorisations":   "valorisations",
    "marche":          "marché",
    "marches":         "marchés",
    "societe":         "société",
    "societes":        "societes",
    "fondamentale":    "fondamentale",
    "fondamentales":   "fondamentales",
    "fondamentaux":    "fondamentaux",
    "rentabilite":     "rentabilité",
    "rentabilites":    "rentabilités",
    "operationnelle":  "opérationnelle",
    "operationnelles": "opérationnelles",
    "operationnel":    "opérationnel",
    "operationnels":   "opérationnels",
    "modele":          "modèle",
    "modeles":         "modèles",
    "tresorerie":      "trésorerie",
    "tresoreries":     "trésoreries",
    "creation":        "création",
    "createur":        "créateur",
    "creatrice":       "créatrice",
    "createurs":       "créateurs",
    "investissement":  "investissement",
    "investissements": "investissements",
    "investisseur":    "investisseur",
    "investisseurs":   "investisseurs",
    "performance":     "performance",
    "performances":    "performances",
    "ecart":           "écart",
    "ecarts":          "écarts",
    "deception":       "déception",
    "deceptions":      "déceptions",
    "ecosysteme":      "écosystème",
    "ecosystemes":     "écosystèmes",
    "ecart-type":      "écart-type",
    "energie":         "énergie",
    "energies":        "énergies",
    "energetique":     "énergétique",
    "agree":           "agréé",
    "ecoute":          "écoute",
    "preference":      "préférence",
    "preferences":     "préférences",
    "diversification": "diversification",
    "concentration":   "concentration",
    "exposition":      "exposition",
    "expositions":     "expositions",
    "ponderation":     "pondération",
    "ponderations":    "pondérations",
    "ponderee":        "pondérée",
    "ponderees":       "pondérées",
    "pondere":         "pondéré",
    "ponderes":        "pondérés",
    "horizon":         "horizon",
    "regulation":      "régulation",
    "regulations":     "régulations",
    "reglementation":  "réglementation",
    "reglementaire":   "réglementaire",
    "reglementaires":  "réglementaires",
    "reglement":       "règlement",
    "regulier":        "régulier",
    "reguliere":       "régulière",
    "regulierement":   "régulièrement",
    "specifique":      "spécifique",
    "specifiques":     "spécifiques",
    "specificite":     "spécificité",
    "specificites":    "spécificités",
    "specifier":       "spécifier",
    "fideliste":       "fidéliste",
    "fidelisation":    "fidélisation",
    "fideliser":       "fidéliser",
    "decision":        "décision",
    "decisions":       "décisions",
    "decisionnel":     "décisionnel",
    "decisionnelle":   "décisionnelle",
    "decisionnels":    "décisionnels",
    "evenement":       "événement",
    "evenements":      "événements",
    "perimetre":       "périmètre",
    "perimetres":      "périmètres",
    "indicateur":      "indicateur",
    "indicateurs":     "indicateurs",
    "matiere":         "matière",
    "matieres":        "matières",
    "premiere":        "première",
    "premieres":       "premières",
    "derniere":        "dernière",
    "dernieres":       "dernières",
    "dernier":         "dernier",
    "derniers":        "derniers",
    "operatoire":      "opératoire",
    "operatoires":     "opératoires",
    "operatif":        "opératif",
    "synthese":        "synthèse",
    "syntheses":       "synthèses",
    "modelisation":    "modélisation",
    "evaluation":      "évaluation",
    "evaluations":     "évaluations",
    "deviation":       "déviation",
    "ecart-type":      "écart-type",
    "ecart type":      "écart type",
    "categorie":       "catégorie",
    "categories":      "catégories",
    "regime":          "régime",
    "regimes":         "régimes",
    "scenario":        "scénario",
    "scenarios":       "scenarios",
    "horizon":         "horizon",
    "objectif":        "objectif",
    "objectifs":       "objectifs",
    "interet":         "intérêt",
    "interets":        "intérêts",
    "credit":          "crédit",
    "credits":         "crédits",
    "perte":           "perte",
    "pertes":          "pertes",
    "deficit":         "déficit",
    "deficits":        "déficits",
    "surperforme":     "surperforme",
    "sous-performe":   "sous-performe",
    "trimestre":       "trimestre",
    "trimestres":      "trimestres",
    "trimestriel":     "trimestriel",
    "trimestrielle":   "trimestrielle",
    "trimestrielles":  "trimestrielles",
    "annuelle":        "annuelle",
    "annuelles":       "annuelles",
    "annuel":          "annuel",
    "annuels":         "annuels",
    "mensuelle":       "mensuelle",
    "mensuelles":      "mensuelles",
    "mensuel":         "mensuel",
    "hebdomadaire":    "hebdomadaire",
    "hebdomadaires":   "hebdomadaires",
    "quotidien":       "quotidien",
    "quotidienne":     "quotidienne",
    "stabilite":       "stabilité",
    "stabilisee":      "stabilisée",
    "stabilisation":   "stabilisation",
    "instabilite":     "instabilité",
    "fragilite":       "fragilité",
    "solidite":        "solidité",
    "solides":         "solides",
    "robustesse":      "robustesse",
    "vulnerabilite":   "vulnérabilité",
    "vulnerabilites":  "vulnérabilités",
    "securite":        "sécurité",
    "securitaire":     "sécuritaire",
    "responsabilite":  "responsabilité",
    "responsabilites": "responsabilités",
    "confidentialite": "confidentialité",
    "confidentielle":  "confidentielle",
    "fidelite":        "fidélité",
    "garantie":        "garantie",
    "garanties":       "garanties",

    # === Adjectifs frequents ===
    "premier":         "premier",
    "premiers":        "premiers",
    "deuxieme":        "deuxième",
    "troisieme":       "troisième",
    "quatrieme":       "quatrième",
    "cinquieme":       "cinquième",
    "general":         "général",
    "generale":        "générale",
    "generales":       "générales",
    "generaux":        "généraux",
    "particulier":     "particulier",
    "particuliere":    "particulière",
    "particuliers":    "particuliers",
    "particulieres":   "particulières",
    "different":       "différent",
    "differente":      "différente",
    "differents":      "différents",
    "differentes":     "différentes",
    "different ":      "différent ",
    "differentie":     "différentié",
    "differential":    "différentiel",
    "differentielle":  "différentielle",
    "elevee":          "élevée",
    "elevees":         "élevées",
    "eleve":           "élevé",
    "eleves":          "élevés",
    "moderne":         "moderne",
    "modere":          "modéré",
    "moderee":         "modérée",
    "moderes":         "modérés",
    "moderees":        "modérées",
    "europeen":        "européen",
    "europeenne":      "européenne",
    "europeens":       "européens",
    "europeennes":     "européennes",
    "americain":       "américain",
    "americaine":      "américaine",
    "americains":      "américains",
    "americaines":     "américaines",
    "indispensable":   "indispensable",
    "necessaire":      "nécessaire",
    "necessaires":     "nécessaires",
    "necessite":       "nécessité",
    "considerable":    "considérable",
    "considerables":   "considérables",
    "exceptionnel":    "exceptionnel",
    "exceptionnelle":  "exceptionnelle",
    "exceptionnels":   "exceptionnels",
    "exceptionnelles": "exceptionnelles",
    "marginal":        "marginal",
    "marginale":       "marginale",
    "marginaux":       "marginaux",
    "complet":         "complet",
    "complete":        "complète",
    "completee":       "complétée",
    "completes":       "complets",

    # === Adverbes / connecteurs ===
    "tres":            "très",
    "deja":            "déjà",
    "apres":           "après",
    "egalement":       "également",
    "specifiquement":  "spécifiquement",
    "particulierement":"particulièrement",
    "generalement":    "généralement",
    "essentiellement": "essentiellement",
    "naturellement":   "naturellement",
    "regulierement":   "régulièrement",
    "evidemment":      "évidemment",
    "anterieurement":  "antérieurement",
    "ulterieurement":  "ultérieurement",
    "prealablement":   "préalablement",

    # === Termes financiers / techniques ===
    "marge nette":          "marge nette",
    "marge brute":          "marge brute",
    "marges":               "marges",
    "rendement":            "rendement",
    "rendements":           "rendements",
    "dividende":            "dividende",
    "dividendes":           "dividendes",
    "remuneration":         "rémunération",
    "remunerations":        "rémunérations",
    "remunere":             "rémunéré",
    "remuneree":            "rémunérée",
    "remuneres":            "rémunérés",
    "actionnaire":          "actionnaire",
    "actionnaires":         "actionnaires",
    "actionnariale":        "actionnariale",
    "actionnariat":         "actionnariat",
    "valeur":               "valeur",
    "valeurs":              "valeurs",
    "mobiliere":            "mobilière",
    "mobilieres":           "mobilières",
    "immobilier":           "immobilier",
    "immobiliere":          "immobilière",
    "immobilieres":         "immobilières",
    "financier":            "financier",
    "financiere":           "financière",
    "financieres":          "financières",
    "financiers":           "financiers",
    "etat":                 "état",
    "etats":                "états",
    "compte":               "compte",
    "comptes":              "comptes",
    "comptable":            "comptable",
    "comptables":           "comptables",
    "manipulation":         "manipulation",
    "manipulations":        "manipulations",
    "manipulee":            "manipulée",
    "manipule":             "manipulé",
    "honoraire":            "honoraire",
    "honoraires":           "honoraires",
    "exercice":             "exercice",
    "exercices":            "exercices",
    "interet":              "intérêt",
    "interets":             "intérêts",
    "couverture":           "couverture",
    "ratio":                "ratio",
    "ratios":               "ratios",
    "agregat":              "agrégat",
    "agregats":             "agrégats",
    "agregation":           "agrégation",
    "ponderee":             "pondérée",
    "ponderation":          "pondération",
    "decote":               "décote",
    "prime":                "prime",
    "secteur":              "secteur",
    "secteurs":             "secteurs",
    "sectoriel":            "sectoriel",
    "sectorielle":          "sectorielle",
    "sectoriels":           "sectoriels",
    "sectorielles":         "sectorielles",
    "indice":               "indice",
    "indices":              "indices",
    "univers":              "univers",
    "panier":               "panier",
    "paniers":              "paniers",

    # === Phrases/expressions tres recurrentes ===
    "Genere par":           "Généré par",
    "genere par":           "généré par",
    "Note :":               "Note :",
    "Source :":             "Source :",
    "Sources :":            "Sources :",
    "Genere":               "Généré",
    "genere":               "généré",
    "Conditions d'invalidation": "Conditions d'invalidation",
    "Risques principaux":   "Risques principaux",
    "Lecture analytique":   "Lecture analytique",
    "Recommandation":       "Recommandation",
    "Synthese":             "Synthèse",
    "Methodologie":         "Méthodologie",
    "Mentions Legales":     "Mentions Légales",
    "Mentions legales":     "Mentions légales",
    "Caractere informatif": "Caractère informatif",
    "Caractere":            "Caractère",
    "Risques associes":     "Risques associés",
    "Performance passee":   "Performance passée",
    "Confidentialite":      "Confidentialité",
    "ne prejugent":         "ne préjugent",
    "prejuge":              "préjuge",
    "Surponderer":          "Surpondérer",
    "Sous-ponderer":        "Sous-pondérer",
    "Reequilibrer":         "Rééquilibrer",
    "Revisable":            "Révisable",
    "Confidentiel":         "Confidentiel",  # déjà ASCII OK
    "S&P 500":              "S&P 500",

    # === SECOND PASS — mots oublies au premier scan ===
    "reelles":              "réelles",
    "reelle":               "réelle",
    "reels":                "réels",
    "reel":                 "réel",
    "basee":                "basée",
    "basees":               "basées",
    "base sur":             "basé sur",
    "analysee":             "analysée",
    "analysees":            "analysées",
    "analyser":             "analyser",
    "analyse":              "analyse",
    "analyses":             "analyses",
    "numerotee":            "numérotée",
    "numerotees":           "numérotées",
    "numerote":             "numéroté",
    "numerotes":            "numérotés",
    "Ecart":                "Écart",
    "ecartez":              "écartez",
    "ecartee":              "écartée",
    "ecartees":             "écartées",
    "etablie":              "établie",
    "etablies":             "établies",
    "etabli":               "établi",
    "etablis":              "établis",
    "ete":                  "été",
    "Etablir":              "Établir",
    "Etat":                 "État",
    "Etats":                "États",
    "aligne":               "aligné",
    "alignee":              "alignée",
    "alignees":             "alignées",
    "alignes":              "alignés",
    "alignement":           "alignement",
    "concentre":            "concentré",
    "concentree":           "concentrée",
    "concentres":           "concentrés",
    "maturite":             "maturité",
    "bilancielle":          "bilancielle",
    "bilanciel":            "bilanciel",
    "bilantielle":          "bilantielle",
    "matures":              "matures",
    "structurel":           "structurel",
    "structurelle":         "structurelle",
    "structurels":          "structurels",
    "structurelles":        "structurelles",
    "premiere":             "première",
    "premieres":            "premières",
    "preferer":             "préférer",
    "preferee":             "préférée",
    "prefere":              "préféré",
    "preferes":             "préférés",
    "preferable":           "préférable",
    "interessant":          "intéressant",
    "interessante":         "intéressante",
    "interessants":         "intéressants",
    "interessantes":        "intéressantes",
    "interesse":            "intéresse",
    "interesser":           "intéresser",
    "etudie":               "étudie",
    "etudie un":            "étudie un",
    "etude":                "étude",
    "etudes":               "études",
    "developpe":            "développe",
    "developpee":           "développée",
    "developpes":           "développés",
    "developpement":        "développement",
    "developpements":       "développements",
    "developper":           "développer",
    "developpeur":          "développeur",
    "developpeurs":         "développeurs",
    "tendance":             "tendance",
    "tendances":            "tendances",
    "perspective":          "perspective",
    "perspectives":         "perspectives",
    "decouvre":             "découvre",
    "decouvert":            "découvert",
    "decouverte":           "découverte",
    "succes":               "succès",
    "exces":                "excès",
    "process":              "process",
    "completee":            "complétée",
    "completes":            "complets",
    "complete":             "complète",
    "completer":            "compléter",
    "complement":           "complément",
    "complementaire":       "complémentaire",
    "complementaires":      "complémentaires",
    "complementarite":      "complémentarité",
    "incoherence":          "incohérence",
    "incoherences":         "incohérences",
    "coherence":            "cohérence",
    "coherent":             "cohérent",
    "coherente":            "cohérente",
    "coherents":            "cohérents",
    "coherentes":           "cohérentes",
    "operee":               "opérée",
    "operees":              "opérées",
    "opere":                "opère",
    "operent":              "opèrent",
    "operer":               "opérer",
    "operation":            "opération",
    "operations":           "opérations",
    "modere":               "modéré",
    "moderement":           "modérément",
    "modere par":           "modéré par",
    "permettre":            "permettre",
    "permet":               "permet",
    "permettant":           "permettant",
    "permis":               "permis",
    "comprend":             "comprend",
    "comprenant":           "comprenant",
    "compris":              "compris",
    "comprenait":           "comprenait",
    "etait":                "était",
    "etaient":              "étaient",
    "etre":                 "être",
    "ete par":              "été par",
    "depend":               "dépend",
    "dependant":            "dépendant",
    "dependance":           "dépendance",
    "dependances":          "dépendances",
    "dependent":            "dépendent",
    "dependu":              "dépendu",
    "dependra":             "dépendra",
    "dependront":           "dépendront",
    "doit etre":            "doit être",
    "doivent etre":         "doivent être",
    "peut etre":            "peut être",
    "peuvent etre":         "peuvent être",
    "regle":                "règle",
    "regles":               "règles",
    "regle absolue":        "règle absolue",
    "completement":         "complètement",
    "ferment":              "ferment",
    "preserver":            "préserver",
    "preserve":             "préserve",
    "preservation":         "préservation",
    "tendances majeures":   "tendances majeures",
    "lies":                 "liés",
    "lien":                 "lien",
    "liens":                "liens",
    "liee":                 "liée",
    "liees":                "liées",
    "lie":                  "lié",
    "deja calcule":         "déjà calculé",
    "calcules":             "calculés",
    "calculee":             "calculée",
    "calculees":            "calculées",
    "calcul":               "calcul",
    "calculs":              "calculs",
    "calculee a":           "calculée à",
    "interpreter":          "interpréter",
    "interpretes":          "interprétés",
    "interpretee":          "interprétée",
    "approfondi":           "approfondi",
    "approfondie":          "approfondie",
    "approfondis":          "approfondis",
    "approfondies":         "approfondies",
    "imprecises":           "imprécises",
    "imprecis":             "imprécis",
    "precis":               "précis",
    "precise":              "précise",
    "preciser":             "préciser",
    "precision":            "précision",
    "precision a":          "précision à",
    "rentabilites":         "rentabilités",
    "lever":                "lever",
    "levee":                "levée",
    "levees":               "levées",
    "decele":               "décèle",
    "deceles":              "décélés",
    "vise":                 "vise",
    "visee":                "visée",
    "vise a":               "vise à",
    "vise une":             "vise une",
    "deroulement":          "déroulement",
    "deroulements":         "déroulements",
    "renvoie":              "renvoie",
    "renvoyer":             "renvoyer",
    "rappel":               "rappel",
    "rappels":              "rappels",
    "rappele":              "rappelé",
    "rappelee":             "rappelée",
    "abondante":            "abondante",
    "abondantes":           "abondantes",
    "concrete":             "concrète",
    "concretes":            "concrètes",
    "concretement":         "concrètement",
    "concret":              "concret",
    "concrets":             "concrets",
    "concretiser":          "concrétiser",
    "concretisation":       "concrétisation",
    "lecture":              "lecture",
    "lectures":             "lectures",
    "lecteur":              "lecteur",
    "lecteurs":             "lecteurs",
    "lecture des":          "lecture des",
    "rotation":             "rotation",
    "rotations":            "rotations",
    "favorable":            "favorable",
    "favorables":           "favorables",
    "favoriser":            "favoriser",
    "favorise":             "favorise",
    "favorisee":            "favorisée",
    "defavorable":          "défavorable",
    "defavorables":         "défavorables",
    "defavorise":           "défavorise",
    "defendre":             "défendre",
    "defense":              "défense",
    "defensive":            "défensive",
    "defensif":             "défensif",
    "defensifs":            "défensifs",
    "defensives":           "défensives",
    "deja":                 "déjà",
    "decennie":             "décennie",
    "decennies":            "décennies",
    "epuisee":              "épuisée",
    "epuise":               "épuisé",
    "epuisement":           "épuisement",
    "deteriore":            "détériore",
    "deteriorent":          "détériorent",
    "deterioration":        "détérioration",
    "evite":                "évite",
    "eviter":               "éviter",
    "evitable":             "évitable",
    "evitables":            "évitables",
    "evite de":             "évite de",
    "evolue dans":          "évolue dans",
    "deboucher":            "déboucher",
    "debouche":             "débouche",
    "deboucle":             "débouclé",
    "deblocage":            "déblocage",
    "supprimee":            "supprimée",
    "supprimes":            "supprimés",
    "supprime":             "supprimé",
    "supprimer":            "supprimer",
    "ajoute":               "ajouté",
    "ajoutee":              "ajoutée",
    "ajoutes":              "ajoutés",
    "ajoutees":             "ajoutées",
    "creer":                "créer",
    "cree":                 "crée",
    "creee":                "créée",
    "crees":                "créés",
    "creees":               "créées",
    "selectivite":          "sélectivité",
    "selection":            "sélection",
    "selectionne":          "sélectionné",
    "selectionnee":         "sélectionnée",
    "selectionnes":         "sélectionnés",
    "selectionnees":        "sélectionnées",
    "selectionner":         "sélectionner",
    "selectionneur":        "sélectionneur",
    "modifie":              "modifié",
    "modifiee":             "modifiée",
    "modifies":             "modifiés",
    "modifiees":            "modifiées",
    "modification":         "modification",
    "modifications":        "modifications",
    "modifier":             "modifier",
    "ferment de":           "ferment de",
    "elargit":              "élargit",
    "elargi":               "élargi",
    "elargis":              "élargis",
    "elargie":              "élargie",
    "elargies":             "élargies",
    "elargissement":        "élargissement",
    "ressource":            "ressource",
    "ressources":           "ressources",
    "depenses":             "dépenses",
    "depense":              "dépense",
    "depensee":             "dépensée",
    "decennie":             "décennie",
    "rentables":            "rentables",
    "rentable":             "rentable",
    "rentabiliser":         "rentabiliser",
    "vehicule":             "véhicule",
    "vehicules":            "véhicules",
    "vehiculer":            "véhiculer",
    "implementer":          "implémenter",
    "implementation":       "implémentation",
    "implemente":           "implémenté",
    "deboucle":             "débouclé",
    "monetiser":            "monétiser",
    "monetisation":         "monétisation",
    "monetise":             "monétisé",
    "monetisee":            "monétisée",
    "complementaire":       "complémentaire",
    "complementaires":      "complémentaires",
    "specifie":             "spécifié",
    "specifiee":            "spécifiée",
    "specifies":            "spécifiés",
    "specifiees":           "spécifiées",
    "expertise":            "expertise",
    "expertises":           "expertises",
    "expert":               "expert",
    "experts":              "experts",
    "evidente":             "évidente",
    "evidentes":            "évidentes",
    "evidents":             "évidents",
    "evident":              "évident",
    "evidence":             "évidence",
    "demontre":             "démontre",
    "demontrer":            "démontrer",
    "demontree":            "démontrée",
    "demontres":            "démontrés",
    "demonstration":        "démonstration",
    "frequence":            "fréquence",
    "frequences":           "fréquences",
    "frequent":             "fréquent",
    "frequente":            "fréquente",
    "frequents":            "fréquents",
    "frequentes":           "fréquentes",
    "fragile":              "fragile",
    "fragiles":             "fragiles",
    "agressif":             "agressif",
    "agressifs":            "agressifs",
    "agressives":           "agressives",
    "agressive":            "agressive",
    "lancement":            "lancement",
    "lancements":           "lancements",
    "lance":                "lance",
    "lancee":               "lancée",
    "lances":               "lancés",
    "lancees":              "lancées",
    "compresseurs":         "compresseurs",
    "convergence":          "convergence",
    "convergences":         "convergences",
    "convergent":           "convergent",
    "convergente":          "convergente",
    "convergentes":         "convergentes",
    "diverge":              "diverge",
    "diverger":             "diverger",
    "divergent":            "divergent",
    "divergente":           "divergente",
    "divergentes":          "divergentes",
    "divergence":           "divergence",
    "divergences":          "divergences",
    "ralentissement":       "ralentissement",
    "accelere":             "accélère",
    "accelerer":            "accélérer",
    "acceleration":         "accélération",
    "accelerees":           "accélérées",
    "acceleration":         "accélération",
    "decelerer":            "décélérer",
    "deceleration":         "décélération",
    "remontee":             "remontée",
    "remontees":            "remontées",
    "remonte":              "remonte",
    "perdurer":             "perdurer",
    "perdure":              "perdure",
    "duree":                "durée",
    "durees":               "durées",
    "intervenir":           "intervenir",
    "intervient":           "intervient",
    "interviennent":        "interviennent",
    "intervention":         "intervention",
    "interventions":        "interventions",
    "consequent":           "conséquent",
    "consequence":          "conséquence",
    "consequences":         "conséquences",
    "consequemment":        "conséquemment",
    "trace":                "trace",
    "tracee":               "tracée",
    "traces":               "traces",
    "subi":                 "subi",
    "subir":                "subir",
    "subie":                "subie",
    "subis":                "subis",
    "deboites":             "déboîtés",
    "alleger":              "alléger",
    "allege":               "allégé",
    "allegee":              "allégée",
    "alleges":              "allégés",
    "allegement":           "allégement",
    "envergure":            "envergure",
    "envergures":           "envergures",
    "deteriore":            "détériore",
    "fragilisee":           "fragilisée",
    "fragiliser":           "fragiliser",
    "saturation":           "saturation",
    "saturer":              "saturer",
    "sature":               "saturé",
    "saturee":              "saturée",
    "potentiel":            "potentiel",
    "potentielle":          "potentielle",
    "potentiels":           "potentiels",
    "potentielles":         "potentielles",
    "potentiellement":      "potentiellement",
    "manageriale":          "managériale",
    "manager":              "manager",
    "managers":             "managers",
    "management":           "management",
    "discipline":           "discipline",
    "disciplinee":          "disciplinée",
    "disciplines":          "disciplinés",
    "discipliner":          "discipliner",
    "discipliner par":      "discipliner par",
    "delai":                "délai",
    "delais":               "délais",
    "delaisser":            "délaisser",
    "delaisse":             "délaissé",
    "presentent":           "présentent",
    "presentation":         "présentation",
    "presentations":        "présentations",
    "presenter":            "présenter",
    "presente sa":          "présente sa",
    "discretion":           "discrétion",
    "discretionnaire":      "discrétionnaire",
    "vraisemblable":        "vraisemblable",
    "vraisemblablement":    "vraisemblablement",
    "veritablement":        "véritablement",
    "veritable":            "véritable",
    "verite":               "vérité",
    "verites":              "vérités",
    "abscence":             "absence",
    "absence":              "absence",
    "absent":               "absent",
    "absente":              "absente",
    "absents":              "absents",
    "absentes":             "absentes",
    "expliquer":            "expliquer",
    "explique":             "explique",
    "explication":          "explication",
    "explications":         "explications",
    "expliquee":            "expliquée",
    "expliquee par":        "expliquée par",
    "expliquees":           "expliquées",
    "expliquees par":       "expliquées par",
    "sous-evalue":          "sous-évalué",
    "sous-evaluee":         "sous-évaluée",
    "sur-evalue":           "sur-évalué",
    "sur-evaluee":          "sur-évaluée",
    "evalue":               "évalué",
    "evaluee":              "évaluée",
    "evaluees":             "évaluées",
    "evalues":              "évalués",
    "demontre":             "démontré",
    "demontree":            "démontrée",
    "etabli":               "établi",
    "etablie":              "établie",
    "etablies":             "établies",
    "etablis":              "établis",
    "amelioree":            "améliorée",
    "ameliorees":           "améliorées",
    "ameliores":            "améliorés",
    "positionne":           "positionné",
    "positionnee":          "positionnée",
    "positionnees":         "positionnées",
    "positionnes":          "positionnés",
    "reglementaire":        "réglementaire",
    "reglementaires":       "réglementaires",
    "reglementations":      "réglementations",
    "reglementation":       "réglementation",
    "strategie":            "stratégie",
    "strategies":           "stratégies",
    "strategique":          "stratégique",
    "strategiques":         "stratégiques",
    "consequence":          "conséquence",
    "consequences":         "conséquences",
    "consequent":           "conséquent",
    "consequente":          "conséquente",
    "Telecoms":             "Télécoms",
    "telecoms":             "télécoms",
    "Materiaux":            "Matériaux",
    "materiaux":            "matériaux",
    "matiere":              "matière",
    "matieres":             "matières",
    "premiere":             "première",
    "premieres":            "premières",
    "matieres premieres":   "matières premières",
    "decelere":             "décélère",
    "deceleration":         "décélération",
    "operationnellement":   "opérationnellement",
    "exclu":                "exclu",
    "exclus":               "exclus",
    "exclusion":            "exclusion",
    "exclure":              "exclure",
    "exclusive":            "exclusive",
    "exclusivement":        "exclusivement",
    "rateaux":              "râteaux",
    "manageria":            "managéria",
    "tete":                 "tête",
    "metres":               "mètres",
    "fete":                 "fête",
    "betes":                "bêtes",
    "donneront":            "donneront",
    "donnera":              "donnera",
    "deboucle":             "débouclé",
    "majeure":              "majeure",
    "majeures":             "majeures",
    "majeurs":              "majeurs",
    "majeur":               "majeur",
    "epargne":              "épargne",
    "epargner":             "épargner",
    "epargnant":            "épargnant",
    "epargnants":           "épargnants",
    "diversifie":           "diversifié",
    "diversifiee":          "diversifiée",
    "diversifies":          "diversifiés",
    "diversifiees":         "diversifiées",
    "deficitaire":          "déficitaire",
    "deficitaires":         "déficitaires",
    "Mises en garde":       "Mises en garde",
    "Limites & Mises en garde": "Limites & Mises en garde",
    "Constructions":        "Constructions",
    "Construction de":      "Construction de",
    "modale":               "modale",
    "module":               "module",
    "modules":              "modules",
    "epicentrale":          "épicentrale",
    "Genere par IA":        "Généré par IA",
    "genere par IA":        "généré par IA",
    "Document genere":      "Document généré",
    "document genere":      "document généré",
    "comment c'est ecrit":  "comment c'est écrit",

    # === THIRD PASS — encore plus de mots ===
    "generer":              "générer",
    "annees":               "années",
    "annee":                "année",
    "integral":             "intégral",
    "integrale":            "intégrale",
    "integrales":           "intégrales",
    "integraux":            "intégraux",
    "integralement":        "intégralement",
    "integralite":          "intégralité",
    "controle":             "contrôle",
    "controles":            "contrôles",
    "controler":            "contrôler",
    "controle des":         "contrôle des",
    "incontrolable":        "incontrôlable",
    "controleurs":          "contrôleurs",
    "deflate":              "déflaté",
    "inflate":              "inflaté",
    "ratifie":              "ratifié",
    "ratifier":             "ratifier",
    "ratification":         "ratification",
    "exclura":              "exclura",
    "abondance":            "abondance",
    "incidence":            "incidence",
    "incidences":           "incidences",
    "decision finale":      "décision finale",
    "Caractere":            "Caractère",
    "caractere":            "caractère",
    "caracteres":           "caractères",
    "caracterise":          "caractérise",
    "caracterisee":         "caractérisée",
    "caracteristique":      "caractéristique",
    "caracteristiques":     "caractéristiques",
    "deterministe":         "déterministe",
    "deterministes":        "déterministes",
    "determination":        "détermination",
    "determine":            "détermine",
    "determinee":           "déterminée",
    "determines":           "déterminés",
    "determinees":          "déterminées",
    "determiner":           "déterminer",
    "determinant":          "déterminant",
    "determinante":         "déterminante",
    "deboucle sur":         "débouclé sur",
    "Genere":               "Généré",
    "Marge brute":          "Marge brute",  # déjà sans accent
    "concentre":            "concentré",
    "geographique":         "géographique",
    "geographiques":        "géographiques",
    "geographiquement":     "géographiquement",
    "geopolitique":         "géopolitique",
    "geopolitiques":        "géopolitiques",
    "geomorphologique":     "géomorphologique",
    "decourager":           "décourager",
    "decourage":            "découragé",
    "encourager":           "encourager",
    "encouragement":        "encouragement",
    "decline":              "décline",
    "declinee":             "déclinée",
    "decliner":             "décliner",
    "decline a":            "décline à",
    "declinent":            "déclinent",
    "declination":          "déclinaison",
    "imposer":              "imposer",
    "impose":               "impose",
    "imposee":              "imposée",
    "imposes":              "imposés",
    "rever":                "rêver",
    "reve":                 "rêve",
    "reves":                "rêves",
    "qualite operationnelle": "qualité opérationnelle",
    "operationnelle inegalee": "opérationnelle inégalée",
    "inegalee":             "inégalée",
    "inegale":              "inégalé",
    "decemment":            "décemment",
    "honnete":              "honnête",
    "honnetete":            "honnêteté",
    "diversite":            "diversité",
    "diversites":           "diversités",
    "infinite":             "infinité",
    "modalite":             "modalité",
    "modalites":            "modalités",
    "modalite suivante":    "modalité suivante",
    "ferment":              "ferment",
    "compresse":            "compressé",
    "compressee":           "compressée",
    "compresses":           "compressés",
    "compression":          "compression",
    "compression du":       "compression du",
    "expansion":            "expansion",
    "expansions":           "expansions",
    "extensible":           "extensible",
    "amplification":        "amplification",
    "Recession":            "Récession",
    "recession":            "récession",
    "recessions":           "récessions",
    "Recente":              "Récente",
    "recente":              "récente",
    "recents":              "récents",
    "recentes":             "récentes",
    "recent":               "récent",
    "Crise":                "Crise",
    "crisee":               "crisée",
    "Decennie":             "Décennie",
    "decennie":             "décennie",
    "Decennies":            "Décennies",
    "decennies":            "décennies",
    "decennal":             "décennal",
    "decennale":            "décennale",
    "Annuel":               "Annuel",
    "Mensuel":              "Mensuel",
    "Trimestre":            "Trimestre",
    "Trimestrielle":        "Trimestrielle",
    "Trimestriel":          "Trimestriel",
    "Hebdomadaire":         "Hebdomadaire",
    "Journalier":           "Journalier",
    "Journalere":           "Journalière",
    "Journaliere":          "Journalière",
    "regularisation":       "régularisation",
    "regulariser":          "régulariser",
    "regularise":           "régularisé",
    "regularisee":          "régularisée",
    "Resumes":              "Résumés",
    "resume":               "résumé",
    "resumes":              "résumés",
    "resume des":           "résumé des",
    "resumee":              "résumée",
    "resumer":              "résumer",
    "Conclusion":           "Conclusion",
    "conclusion":           "conclusion",
    "conclusions":          "conclusions",
    "conclure":             "conclure",
    "conclu":               "conclu",
    "concluent":            "concluent",
    "concluant":            "concluant",
    "Choix":                "Choix",  # déjà OK
    "Choix prefere":        "Choix préféré",
    "choix prefere":        "choix préféré",
    "Choix prefere :":      "Choix préféré :",
    "selon le profil":      "selon le profil",
    "ramene":               "ramène",
    "ramener":              "ramener",
    "ramenee":              "ramenée",
    "ramenes":              "ramenés",
    "delete":               "delete",
    "trace de":             "trace de",
    "traces de":            "traces de",
    "echelle":              "échelle",
    "echelles":             "échelles",
    "echeance":             "échéance",
    "echeances":            "échéances",
    "echelonne":            "échelonné",
    "echelonnee":           "échelonnée",
    "Echelle":              "Échelle",
    "Echeance":             "Échéance",
    "rebalance":            "rebalance",  # anglicisme courant
    "rebalancer":           "rebalancer",
    "rebalancement":        "rebalancement",
    "ferme la":             "ferme la",
    "ferme le":             "ferme le",
    "fermes":               "fermes",
    "ouvre la":             "ouvre la",
    "decompose":            "décompose",
    "decomposes":           "décomposés",
    "decomposee":           "décomposée",
    "decomposition":        "décomposition",
    "Note":                 "Note",  # déjà OK
    "note explicative":     "note explicative",
    "Lecture":              "Lecture",  # déjà OK
    "Lectures":             "Lectures",
    "lecture des":          "lecture des",
    "Cumulee":              "Cumulée",
    "cumulee":              "cumulée",
    "cumule":               "cumulé",
    "cumules":              "cumulés",
    "cumulees":              "cumulées",
    "cumul":                "cumul",

    # === FOURTH PASS — titres et mots-cles encore manquants ===
    "comparee":             "comparée",
    "comparees":            "comparées",
    "compare":              "comparé",   # Note : en EN c'est "compare" mais nous parlons FR
    "compares":             "comparés",
    "comparer":             "comparer",
    "comparable":           "comparable",
    "comparables":          "comparables",
    "comparatif":           "comparatif",
    "comparatifs":          "comparatifs",
    "comparative":          "comparative",
    "comparatives":         "comparatives",
    "boursiere":            "boursière",
    "boursieres":           "boursières",
    "boursier":             "boursier",
    "boursiers":            "boursiers",
    "bourse":               "bourse",
    "bourses":              "bourses",
    "criteres":             "critères",
    "critere":              "critère",
    "Multi-Criteres":       "Multi-Critères",
    "multi-criteres":       "multi-critères",
    "resultat":             "résultat",
    "resultats":            "résultats",
    "resulte":              "résulte",
    "resulter":             "résulter",
    "resultant":            "résultant",
    "Compte de Resultat":   "Compte de Résultat",
    "liquidite":            "liquidité",
    "liquidites":           "liquidités",
    "liquide":              "liquide",
    "liquides":             "liquides",
    "theses":               "thèses",
    "these":                "thèse",
    "Theses":               "Thèses",
    "These":                "Thèse",
    "tete":                 "tête",
    "tete a tete":          "tête à tête",
    "Tete":                 "Tête",
    "etranger":             "étranger",
    "etrangere":            "étrangère",
    "etrangeres":           "étrangères",
    "etrangers":            "étrangers",
    "etranger":             "étranger",
    "frais":                "frais",
    "frequemment":          "fréquemment",
    "Profil":               "Profil",  # déjà OK
    "Profiler":             "Profiler",
    "Capital Allocation":   "Capital Allocation",  # EN dans contexte FR OK
    "Synthese":             "Synthèse",
    "Theses d'Investissement": "Thèses d'Investissement",
    "These d'Investissement":  "Thèse d'Investissement",
    "These d'allocation":   "Thèse d'allocation",
    "ne prejugent":         "ne préjugent",
    "Sommaire":             "Sommaire",  # déjà OK
    "Recapitulatif":        "Récapitulatif",
    "recapitulatif":        "récapitulatif",
    "Recapitulatifs":       "Récapitulatifs",
    "modulee":              "modulée",
    "decennale":            "décennale",
    "Decision":             "Décision",
    "decision":             "décision",
    "Decisions":            "Décisions",
    "Generation":           "Génération",
    "Generee":              "Générée",
    "Generes":              "Générés",
    "Generations":          "Générations",
    "Generee par":          "Générée par",
    "Genere par":           "Généré par",
    "Generes par":          "Générés par",
    "Differentiel":         "Différentiel",
    "differentiel":         "différentiel",
    "Differentielle":       "Différentielle",
    "differentielle":       "différentielle",
    "Differentiation":      "Différentiation",
    "differentiation":      "différentiation",
    "Differentiel de":      "Différentiel de",
    "differentier":         "différentier",
    "Decoupage":            "Découpage",
    "decoupage":            "découpage",
    "Decoupes":             "Découpés",
    "decoupes":             "découpés",
    "Decoupee":             "Découpée",
    "decoupee":             "découpée",
    "Decompte":             "Décompte",
    "decompte":             "décompte",
    "Aper&ccedil;u":        "Aperçu",
    "Apercu":               "Aperçu",
    "apercu":               "aperçu",
    "Apercus":              "Aperçus",
    "apercus":              "aperçus",
    "Donnee":               "Donnée",
    "Donnees":              "Données",
    "Marche":               "Marché",  # ATTN : "marche" verb peut être vrai mais rare en strings
    "Marches":              "Marchés",
    "Donneur":              "Donneur",
    "Donneurs":             "Donneurs",
    "ferme":                "ferme",
    "fermee":               "fermée",
    "expedier":             "expédier",
    "expedie":              "expédié",
    "expedition":           "expédition",
    "Decret":               "Décret",
    "decret":                "décret",
    "Decrets":               "Décrets",
    "Frequemment":           "Fréquemment",
    "frequemment":           "fréquemment",
    "elabore":               "élabore",
    "elaboree":              "élaborée",
    "elaborees":             "élaborées",
    "elabores":              "élaborés",
    "fortement":             "fortement",  # déjà OK
    "Decompose":             "Décompose",
    "Decomposition":         "Décomposition",
    "Decomposees":           "Décomposées",
    "decomposees":           "décomposées",
    "Recurrence":            "Récurrence",
    "recurrence":            "récurrence",
    "Recurrent":             "Récurrent",
    "recurrent":             "récurrent",
    "Recurrente":            "Récurrente",
    "recurrente":            "récurrente",
    "Recurrents":            "Récurrents",
    "recurrents":            "récurrents",
    "Recurrentes":           "Récurrentes",
    "recurrentes":           "récurrentes",
    "Resilience":            "Résilience",
    "resilience":            "résilience",
    "Resilient":             "Résilient",
    "resilient":             "résilient",
    "Resiliente":            "Résiliente",
    "resiliente":            "résiliente",
    "Resilients":            "Résilients",
    "resilients":            "résilients",
    "Resilientes":           "Résilientes",
    "resilientes":           "résilientes",
    "Reverse":               "Reverse",  # EN OK
    "Re-rating":             "Re-rating",  # EN OK
    "re-rating":             "re-rating",
    "Resoudre":              "Résoudre",
    "resoudre":              "résoudre",
    "Resolution":            "Résolution",
    "resolution":            "résolution",
    "Resolutions":           "Résolutions",
    "resolutions":           "résolutions",
    "Resolu":                "Résolu",
    "resolu":                "résolu",
    "Resolus":               "Résolus",
    "resolus":               "résolus",
    "Resolue":               "Résolue",
    "resolue":               "résolue",
    "Resolues":              "Résolues",
    "resolues":              "résolues",
    "Equipe":                "Équipe",
    "equipe":                "équipe",
    "Equipes":               "Équipes",
    "equipes":               "équipes",
    "Equipement":            "Équipement",
    "equipement":            "équipement",
    "Equilibre":             "Équilibre",
    "equilibre":             "équilibre",
    "Equilibres":            "Équilibres",
    "equilibres":            "équilibres",
    "Equilibree":            "Équilibrée",
    "equilibree":            "équilibrée",
    "Equilibrer":            "Équilibrer",
    "equilibrer":            "équilibrer",
    "Equite":                "Équité",
    "equite":                "équité",
    "Equitablement":         "Équitablement",
    "equitablement":         "équitablement",
    "Equitable":             "Équitable",
    "equitable":             "équitable",
    "Equivalent":            "Équivalent",
    "equivalent":            "équivalent",
    "Equivalence":           "Équivalence",
    "equivalence":           "équivalence",
    "Equivalents":           "Équivalents",
    "equivalents":           "équivalents",
    "Equivalence de":        "Équivalence de",
    "Estimes":               "Estimés",
    "Estimee":               "Estimée",
    "Estimer":               "Estimer",
    "Estimateur":            "Estimateur",
    "estimateur":            "estimateur",
    "Estimateurs":           "Estimateurs",
    "estimateurs":           "estimateurs",
    "Estimation":            "Estimation",  # déjà OK
    "rapporte":              "rapporte",  # déjà OK
    "rapportes":             "rapportés",
    "rapportee":             "rapportée",
    "rapportees":            "rapportées",
    "Reflete":               "Reflète",
    "reflete":               "reflète",
    "Reflets":               "Reflets",
    "reflets":               "reflets",
    "Reflexion":             "Réflexion",
    "reflexion":             "réflexion",
    "Reflexions":            "Réflexions",
    "reflexions":            "réflexions",
    "Reflechi":              "Réfléchi",
    "reflechi":              "réfléchi",
    "Reflechir":             "Réfléchir",
    "reflechir":             "réfléchir",
    "Reflechie":             "Réfléchie",
    "reflechie":             "réfléchie",
    "Realise":               "Réalisé",
    "realise":               "réalisé",
    "Realises":              "Réalisés",
    "realises":              "réalisés",
    "Realisee":              "Réalisée",
    "realisee":              "réalisée",
    "Realisees":             "Réalisées",
    "realisees":             "réalisées",
    "Realiser":              "Réaliser",
    "realiser":              "réaliser",
    "Realisation":           "Réalisation",
    "realisation":           "réalisation",
    "Realisations":          "Réalisations",
    "realisations":          "réalisations",
    "Realiste":              "Réaliste",
    "realiste":              "réaliste",
    "Realistes":             "Réalistes",
    "realistes":             "réalistes",
    "Realisme":              "Réalisme",
    "realisme":              "réalisme",
    "Mise a jour":           "Mise à jour",
    "mise a jour":           "mise à jour",
    "Mises a jour":          "Mises à jour",
    "mises a jour":          "mises à jour",
    "a jour":                "à jour",
    "Pas a pas":             "Pas à pas",
    "pas a pas":             "pas à pas",
    "Etape":                 "Étape",
    "etape":                 "étape",
    "Etapes":                "Étapes",
    "etapes":                "étapes",
    "Recap":                 "Récap",
    "recap":                 "récap",
    "vise a":                "vise à",
    "tete":                  "tête",
    "metres":                "mètres",
    "fete":                  "fête",
    "betes":                 "bêtes",
    "rassembleur":           "rassembleur",
    "ferme operationnelle":  "ferme opérationnelle",
    "Operationnel":          "Opérationnel",
    "operationnel":          "opérationnel",
    "Operationnelle":        "Opérationnelle",
    "operationnelle":        "opérationnelle",
    "Operationnels":         "Opérationnels",
    "operationnels":         "opérationnels",
    "Operationnelles":       "Opérationnelles",
    "operationnelles":       "opérationnelles",

    # === FIFTH PASS — derniers correctifs textes courants ===
    "medianes":              "médianes",
    "mediane":               "médiane",
    "median":                "médian",
    "medians":               "médians",
    "Mediane":               "Médiane",
    "Medianes":              "Médianes",
    "Median":                "Médian",
    "aggregats":             "agrégats",
    "aggregat":              "agrégat",
    "aggregation":           "agrégation",
    "aggrege":               "agrégé",
    "aggregee":              "agrégée",
    "aggreges":              "agrégés",
    "Aggregats":             "Agrégats",
    "sensibilite":           "sensibilité",
    "sensibilites":          "sensibilités",
    "Sensibilite":           "Sensibilité",
    "Sensibilites":          "Sensibilités",
    "sensible":              "sensible",
    "sensibles":             "sensibles",
    "economique":            "economique",
    "economiques":           "économiques",
    "economiquement":        "économiquement",
    "Economique":            "Économique",
    "Economiques":           "Économiques",
    "economie":              "économie",
    "economies":             "économies",
    "Economie":              "Économie",
    "Economies":             "Économies",
    "Economiste":            "Économiste",
    "economiste":            "économiste",
    "economistes":           "économistes",
    "normalise":             "normalisé",
    "normalisee":            "normalisée",
    "normalises":            "normalisés",
    "normalisees":           "normalisées",
    "normaliser":            "normaliser",
    "normalisation":         "normalisation",
    "Normalise":             "Normalisé",
    "Normalisee":            "Normalisée",
    "Normalisation":         "Normalisation",
    "verse":                 "versé",  # mais attention : le verbe "verse" sera modifié aussi
    "versee":                "versée",
    "verses":                "versés",
    "versees":               "versées",
    "verser":                "verser",
    "versement":             "versement",
    "versements":            "versements",
    "reinvestissement":      "réinvestissement",
    "reinvestissements":     "réinvestissements",
    "reinvestir":            "réinvestir",
    "reinvesti":             "réinvesti",
    "reinvestie":            "réinvestie",
    "reinvestis":            "réinvestis",
    "etant":                 "étant",
    "Etant":                 "Étant",
    "penalise":              "pénalisé",
    "penalises":             "pénalisés",
    "penalisee":             "pénalisée",
    "penalisees":            "pénalisées",
    "penaliser":             "pénaliser",
    "penalite":              "pénalité",
    "penalites":             "pénalités",
    "renseigne":             "renseigné",
    "renseignee":            "renseignée",
    "renseignes":            "renseignés",
    "renseignees":           "renseignées",
    "renseigner":            "renseigner",
    "renseignement":         "renseignement",
    "mecanique":             "mécanique",
    "mecaniques":            "mécaniques",
    "Mecanique":             "Mécanique",
    "Mecaniques":            "Mécaniques",
    "mecaniquement":         "mécaniquement",
    "ajuste":                "ajusté",
    "ajustes":               "ajustés",
    "ajustee":               "ajustée",
    "ajustees":              "ajustées",
    "ajustement":            "ajustement",
    "ajustements":           "ajustements",
    "ajuster":               "ajuster",
    "Ajuste":                "Ajusté",
    "Ajustement":            "Ajustement",
    "debordement":           "débordement",
    "debordements":          "débordements",
    "deborde":               "déborde",
    "deborder":              "déborder",
    "Cote a cote":           "Côte à côte",
    "cote a cote":           "côte à côte",
    "Cote-a-cote":           "Côte-à-côte",
    "cote-a-cote":           "côte-à-côte",
    "Cote":                  "Côte",  # peut etre risque mais OK
    "cote":                  "côté",  # ATTN ambigu : "côté" ou "coté"
    "cotee":                 "cotée",
    "cotees":                "cotées",
    "cotes":                 "cotés",
    "Cotee":                 "Cotée",
    "Cotees":                "Cotées",
    "Cotes":                 "Cotés",
    "Coter":                 "Coter",
    "couter":                "coûter",
    "coute":                 "coûte",
    "coutent":               "coûtent",
    "couts":                 "coûts",
    "cout":                  "coût",
    "Cout":                  "Coût",
    "Couts":                 "Coûts",
    "couteux":               "coûteux",
    "couteuse":              "coûteuse",
    "couteuses":             "coûteuses",
    "Couteux":               "Coûteux",
    "Couteuse":              "Coûteuse",
    "Couteuses":             "Coûteuses",
    "Cycle":                 "Cycle",  # déjà OK
    "Cycles":                "Cycles",
    "cycle":                 "cycle",
    "cycles":                "cycles",
    "cyclique":              "cyclique",
    "cycliques":             "cycliques",
    "Cyclique":              "Cyclique",
    "Cycliques":             "Cycliques",
    "Cyclicite":             "Cyclicité",
    "cyclicite":             "cyclicité",
    "Cyclicites":            "Cyclicités",
    "cyclicites":            "cyclicités",

    # === SIXTH PASS — contenu sectoriel statique ===
    "Acceleration":          "Accélération",
    "acceleration":          "accélération",
    "Accelerations":         "Accélérations",
    "accelerations":         "accélérations",
    "Souverainete":          "Souveraineté",
    "souverainete":          "souveraineté",
    "Souverainetes":         "Souverainetés",
    "entrainerait":          "entraînerait",
    "entraine":              "entraîne",
    "entrainer":             "entraîner",
    "entrainee":             "entraînée",
    "entraines":             "entraînés",
    "entrainees":            "entraînées",
    "entrainent":            "entraînent",
    "entrainement":          "entraînement",
    "Entraine":              "Entraîne",
    "Entraines":             "Entraînés",
    "Entrainerait":          "Entraînerait",
    "surcout":               "surcoût",
    "surcouts":              "surcoûts",
    "Surcout":               "Surcoût",
    "Surcouts":              "Surcoûts",
    "conformite":            "conformité",
    "conformites":           "conformités",
    "Conformite":            "Conformité",
    "standardise":           "standardisé",
    "standardisee":          "standardisée",
    "standardises":          "standardisés",
    "standardisees":         "standardisées",
    "Standardisation":       "Standardisation",  # déjà OK
    "asiatique":             "asiatique",  # déjà OK
    "asiatiques":            "asiatiques",  # déjà OK
    "Asie":                  "Asie",  # déjà OK
    "europeenne":            "européenne",  # déjà ajouté mais double check
    "europeennes":           "européennes",
    "europeen":              "européen",
    "europeens":             "européens",
    "americain":             "américain",
    "americaine":            "américaine",
    "americains":            "américains",
    "americaines":           "américaines",
    "Americain":             "Américain",
    "Americaine":            "Américaine",
    "Americains":            "Américains",
    "Americaines":           "Américaines",
    "Americain":             "Américain",
    "africain":              "africain",
    "africaine":             "africaine",
    "africains":             "africains",
    "africaines":            "africaines",
    "Africain":              "Africain",
    "Africaine":             "Africaine",
    "baissiere":             "baissière",
    "baissieres":            "baissières",
    "baissier":              "baissier",
    "baissiers":             "baissiers",
    "haussier":              "haussier",
    "haussiere":             "haussière",
    "haussieres":            "haussières",
    "haussiers":             "haussiers",
    "Reouverture":           "Réouverture",
    "reouverture":           "réouverture",
    "Reouvertures":          "Réouvertures",
    "reouvertures":          "réouvertures",
    "conglomerats":          "conglomérats",
    "conglomerat":           "conglomérat",
    "biotech":               "biotech",  # déjà OK
    "biotechs":              "biotechs",
    "vieillissement":        "vieillissement",  # déjà OK
    "Marche":                "Marché",  # déjà OK ajout reconfirme
    "Marches":               "Marchés",
    "marche":                "marché",
    "marches":               "marchés",
    "approfondi":            "approfondi",  # déjà OK
    "porte par":             "porté par",
    "porte vers":            "porté vers",
    "portee par":            "portée par",
    "portees par":           "portées par",
    "portes par":            "portés par",
    "portees":               "portées",
    "portee":                "portée",
    "portes":                "portés",
    "porte":                 "porté",
    "Portee":                "Portée",
    "Porte":                 "Porté",
    "Portees":               "Portées",
    "imprime":               "imprime",  # déjà OK
    "imprimee":              "imprimée",
    "imprimes":              "imprimés",
    "Reduction":             "Réduction",
    "reduction":             "réduction",
    "Reductions":            "Réductions",
    "reductions":            "réductions",
    "reduit":                "réduit",
    "reduits":               "réduits",
    "reduite":               "réduite",
    "reduites":              "réduites",
    "reduire":               "réduire",
    "reducteur":             "réducteur",
    "Reducteurs":            "Réducteurs",
    "Revision":              "Révision",
    "revision":              "révision",
    "Revisions":             "Révisions",
    "revisions":             "révisions",
    "revise":                "révisé",
    "revisee":               "révisée",
    "revises":               "révisés",
    "revisees":              "révisées",
    "reviser":               "réviser",
    "Revise":                "Révisé",
    "approuvee":             "approuvée",
    "approuve":              "approuvé",
    "approuves":             "approuvés",
    "approuvees":            "approuvées",
    "approuver":             "approuver",
    "Plebiscite":            "Plébiscité",
    "plebiscite":            "plébiscité",
    "plebiscitee":           "plébiscitée",
    "plebiscites":           "plébiscités",
}

# Stop-words : tokens jamais a remplacer (techniques, codes, etc.)
SKIP_TOKENS = {
    "S&P", "P/E", "EV/EBITDA", "ROE", "ROIC", "ROA", "EBIT", "EBITDA",
    "FCF", "NOPAT", "DCF", "WACC", "VaR", "CAGR", "EPS", "FY", "ESG",
    "AMF", "CIF", "BCE", "Fed", "PIB", "PMI", "IA", "USD", "EUR", "GBP",
}


def _is_in_string(line: str, pos: int) -> bool:
    """Determine si la position 'pos' est a l'interieur d'une string Python.

    Heuristique simple : compte les triple-quotes et single/double quotes
    avant pos. Pas parfait pour les f-strings imbriquees mais suffisant.
    """
    # Verifier si la ligne commence par # (commentaire) — si oui, traiter comme du texte
    stripped = line.lstrip()
    if stripped.startswith("#"):
        # commentaire complet : on traite tout le contenu apres # comme du texte
        comment_idx = line.find("#")
        return pos > comment_idx

    # Compter les delimiteurs " et ' avant pos (en tenant compte des escapes)
    n_double = 0
    n_single = 0
    i = 0
    while i < pos and i < len(line):
        c = line[i]
        if c == "\\" and i + 1 < len(line):
            i += 2
            continue
        if c == '"':
            n_double += 1
        elif c == "'":
            n_single += 1
        i += 1
    return (n_double % 2 == 1) or (n_single % 2 == 1)


def _preserve_case(original: str, replacement: str) -> str:
    """Préserve la casse du match (Title, UPPER, lower)."""
    if not original or not replacement:
        return replacement
    if original.isupper() and len(original) > 1:
        return replacement.upper()
    if original[0].isupper():
        return replacement[0].upper() + replacement[1:]
    return replacement


# Build a single combined regex compiled once
def restore_accents_in_text(text: str) -> str:
    """Restore accents dans du texte libre (sortie LLM, plain text).

    Contrairement à transform_line() qui opère sur du code Python (avec guard
    _is_in_string), cette version traite n'importe quel texte. Utilisable sur
    les chaînes JSON renvoyées par Groq llama-3.3 qui omet souvent les
    accents malgré les instructions système.
    """
    global _COMBINED_RE
    if _COMBINED_RE is None:
        _COMBINED_RE = _build_combined_regex()
    if not text:
        return text
    def _repl(m):
        actual = m.group(0)
        new_val = _LOWER_MAP.get(actual.lower())
        if new_val is None or actual == new_val:
            return actual
        return _preserve_case(actual, new_val)
    return _COMBINED_RE.sub(_repl, text)


def _build_combined_regex():
    """Construit UN seul gros regex (a1|a2|a3|...) compile une fois.
    Trie par longueur desc pour que les sous-chaines plus longues soient
    matchees en premier."""
    # Filtrer les keys identiques a value (case-insensitive)
    keys = [k for k, v in REPLACEMENTS.items() if k.lower() != v.lower()]
    keys = sorted(set(keys), key=lambda k: -len(k))
    # Lookbehind exclut aussi `.` `/` `-` : evite de matcher dans les MIME types
    # (`presentationml.presentation`), URLs, et Python identifiers (`_present_var`)
    pattern = (
        r'(?<![A-Za-zÀ-ÿ./_-])(?:'
        + "|".join(re.escape(k) for k in keys)
        + r')(?![A-Za-zÀ-ÿ_-])'
    )
    return re.compile(pattern, flags=re.IGNORECASE)


_LOWER_MAP = {k.lower(): v for k, v in REPLACEMENTS.items() if k.lower() != v.lower()}
_COMBINED_RE = None


def transform_line(line: str) -> tuple[str, int]:
    """Applique tous les remplacements en UN seul pass via regex combine."""
    global _COMBINED_RE
    if _COMBINED_RE is None:
        _COMBINED_RE = _build_combined_regex()

    n_changes = 0
    result = []
    last = 0
    for m in _COMBINED_RE.finditer(line):
        start = m.start()
        end = m.end()
        if not _is_in_string(line, start):
            continue
        actual = m.group(0)
        new_val = _LOWER_MAP.get(actual.lower())
        if new_val is None or actual == new_val:
            continue
        replaced = _preserve_case(actual, new_val)
        result.append(line[last:start])
        result.append(replaced)
        last = end
        n_changes += 1
    if result:
        result.append(line[last:])
        return "".join(result), n_changes
    return line, 0


def _ast_accented_identifiers(src: str) -> set[str]:
    """Retourne les identifiants Python (Name, Attribute, FunctionDef, arg, dict
    string keys) qui contiennent des accents. Sert de garde-fou pour eviter que
    restore_accents.py ne casse silencieusement des variables Python."""
    import ast as _ast
    import re as _re
    _ACCENTED = _re.compile(r'[éèêëàâäùûüôöïîçÉÈÊËÀÂÄÙÛÜÔÖÏÎÇ]')
    found = set()
    try:
        tree = _ast.parse(src)
    except SyntaxError:
        return found
    for node in _ast.walk(tree):
        if isinstance(node, _ast.Name) and _ACCENTED.search(node.id):
            found.add(("Name", node.id))
        elif isinstance(node, _ast.Attribute) and _ACCENTED.search(node.attr):
            found.add(("Attribute", node.attr))
        elif isinstance(node, _ast.FunctionDef) and _ACCENTED.search(node.name):
            found.add(("FunctionDef", node.name))
        elif isinstance(node, _ast.arg) and _ACCENTED.search(node.arg):
            found.add(("Arg", node.arg))
        # String literals qui ressemblent a des identifiers Python (snake_case
        # ou avec underscore). Heuristique : doit contenir un `_` OU commencer
        # par minuscule sans capitalisation francaise. Filtre les vrais mots
        # francais comme "Surpondérer", "Santé", "Énergie".
        elif isinstance(node, _ast.Constant) and isinstance(node.value, str):
            v = node.value
            if (_ACCENTED.search(v) and len(v) < 30 and "_" in v):
                # ASCII-fier pour tester si ressemble a un identifier Python
                _from = "éèêëàâäùûüôöïîçÉÈÊËÀÂÄÙÛÜÔÖÏÎÇ"
                _to   = "eeeeaaauuuooiicEEEEAAAUUUOOIIC"
                _ascii = v.translate(str.maketrans(_from, _to))
                if _re.match(r'^[a-z_][a-z0-9_]*$', _ascii):
                    found.add(("StringIdentifier", v))
    return found


def transform_file(path: Path) -> tuple[int, int]:
    """Transforme un fichier en place. Retourne (lines_changed, total_replacements).

    GARDE-FOU AST : si la transformation cree des nouveaux identifiants Python
    avec accents (qui causeraient NameError au runtime), on REVERT le fichier
    et on signale l'erreur. Idem pour les string-identifiers (cles dict).
    """
    src = path.read_text(encoding="utf-8")

    # AST audit AVANT
    accented_before = _ast_accented_identifiers(src)

    lines = src.split("\n")
    new_lines = []
    total = 0
    changed = 0
    for line in lines:
        new_line, n = transform_line(line)
        if n > 0:
            changed += 1
            total += n
        new_lines.append(new_line)
    new_src = "\n".join(new_lines)

    if new_src == src:
        return changed, total

    # AST audit APRES
    accented_after = _ast_accented_identifiers(new_src)
    new_broken = accented_after - accented_before
    if new_broken:
        # REVERT : ne pas ecrire le fichier, signaler l'erreur
        print(f"  [SKIP] {path.name} : restore_accents aurait cree des identifiants Python brises :")
        for kind, name in sorted(new_broken):
            print(f"           {kind:18s} {name!r}")
        print(f"           -> Revert (fichier non modifie). Investiguer manuellement.")
        return 0, 0

    path.write_text(new_src, encoding="utf-8")
    return changed, total


def main():
    targets = [
        # Comparatif societe (cas 1) — renommes en cmp_societe_*_writer
        ROOT / "outputs" / "cmp_societe_pptx_writer.py",
        ROOT / "outputs" / "cmp_societe_pdf_writer.py",
        ROOT / "outputs" / "cmp_societe_xlsx_writer.py",
        # Comparatif sectoriel (cas 2)
        ROOT / "outputs" / "cmp_secteur_pptx_writer.py",
        ROOT / "outputs" / "cmp_secteur_pdf_writer.py",
        ROOT / "outputs" / "cmp_secteur_xlsx_writer.py",
        # Comparatif indice (cas 3) — renommes en cmp_indice_*_writer
        ROOT / "outputs" / "cmp_indice_pptx_writer.py",
        ROOT / "outputs" / "cmp_indice_pdf_writer.py",
        ROOT / "outputs" / "cmp_indice_xlsx_writer.py",
        # Rapport individuel societe (Baptiste : sauf pdf_writer.py qu'il refait)
        ROOT / "outputs" / "pptx_writer.py",
        ROOT / "outputs" / "excel_writer.py",
        ROOT / "outputs" / "briefing.py",
        # Rapport indice
        ROOT / "outputs" / "indice_pptx_writer.py",
        ROOT / "outputs" / "indice_pdf_writer.py",
        ROOT / "outputs" / "indice_excel_writer.py",
        # Screening
        ROOT / "outputs" / "screening_writer.py",
        # Contenu sectoriel statique (catalyseurs/risques utilises par cmp_secteur)
        ROOT / "outputs" / "sectoral_pptx_writer.py",
        # Interface Streamlit (chaines visibles utilisateur)
        ROOT / "app.py",
    ]
    print("=" * 70)
    print("  RESTORE ACCENTS — Bulk transformation")
    print("=" * 70)
    grand_total = 0
    for path in targets:
        if not path.exists():
            print(f"  [SKIP] {path.name} (not found)")
            continue
        changed, total = transform_file(path)
        grand_total += total
        print(f"  {path.name:<40} {changed:>4} lines, {total:>4} replacements")
        # Verif syntaxe
        try:
            py_compile.compile(str(path), doraise=True)
            print(f"  {'':<40}      [OK syntax]")
        except py_compile.PyCompileError as e:
            print(f"  {'':<40}      [FAIL syntax] {e.msg}")
            sys.exit(1)
    print("-" * 70)
    print(f"  TOTAL : {grand_total} replacements")
    print("=" * 70)


if __name__ == "__main__":
    main()
